name: Test Workflow

on: [push] 
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        #This step uses the actions/setup-python@v4 action to install the 
        #specified version of the python (this example uses v3.x which is the latest minor version in 3.x series). 
        #This puts both the python commands in your PATH.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        #The run keyword tells the job to execute a command on the runner.
        #installs pip and flake 8 also if requirements.txt is present then installs all the dependencies specified there
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          python -m pip install freezegun
          python -m pip install requests
          python -m pip install flask-cors
          python -m pip install flask
          python -m pip install flask_sqlalchemy
          python -m pip install datetime
          python -m pip install mysql
          python -m pip install mysql-connector
          python -m pip install flask_testing
          python -m pip install python-dotenv
          #TODO: Install flak8 using pip command here
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Lint with flake8
        #runs flake8 over the code
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      
      - name: Test with unittest
        #runs the unittest
        run: |
          python unit_test.py
         
      - name: Test with integrationtest
        #runs the integrationtest
        run: |
          #TODO: Add the command to run all the integrationtest here.
          python integration_test.py
     
       
